Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,36 +1,52 @@
-# This is a basic workflow to help you get started with Actions
-
-name: CI
-
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+name: "Logseq Publish"
+description: "Publish your Logseq Graph"
+inputs:
+  src:
+    description: "export source"
+    required: true
+    default: ""
+  dest:
+    description: "export destination"
+    required: true
+    default: "www"
+  version:
+    description: >
+      Logseq version to use. Note, not all version are supported.
+      Use "master" if you are not sure what to put here
+    required: true
+    default: "master"
+  trace:
+    type: boolean
+    required: false
+    description: >
+      Whether or not to generate trace file for debugging.  
+    default: true
+branding:
+  icon: "arrow-up-circle"
+  color: "green"
+runs:
+  using: "composite"
+  steps:
+    - name: Create dest before running docker
+      shell: bash
+      run: mkdir -p ${{ github.workspace }}/${{ inputs.dest }}
+    - uses: addnab/docker-run-action@v3
+      with:
+        image: "ghcr.io/pengx17/logseq-publish:${{ inputs.version }}"
+        options: |
+          -v ${{ github.workspace }}:/home/logseq/graph
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          xvfb-run node publish.mjs -p graph/${{ inputs.src }} -t ${{ inputs.trace }} -o graph/${{ inputs.dest }}
+          exit $?
+    - name: change exported files owner
+      shell: bash
+      run: |
+        sudo chown -R $USER: ${{ github.workspace }}/${{ inputs.dest }}
+    - name: Archive trace file
+      # always() makes sure this step will run even if previous step fails
+      if: ${{ always() && inputs.trace }}
+      uses: actions/upload-artifact@v2
+      with:
+        name: trace
+        path: |
+          ${{ inputs.dest }}/trace.zip
